[build]
  command   = "npm run build"
  publish   = ".next"
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "dpkfecuo8"
  deliveryType = "upload"
  imagesPath = "/portfolio"